// ═══════════════════════════════════════════════════════════════════════════
// Données de référence de l'analyseur d'ancres (anchor-text) — extraites pour
// alléger le module principal. Tables PURES (aucune logique) : catégories
// thématiques et groupes de synonymes. Consommées par anchor-text.analyzer.ts.
// ═══════════════════════════════════════════════════════════════════════════

// ─────────────────────────────────────────────────────────────────────────────
// Catégories thématiques — bonus si ancre ET href appartiennent à la même catégorie
// ─────────────────────────────────────────────────────────────────────────────
export const CATEGORIES: Array<{ words: string[]; paths: string[] }> = [
  {
    // Contact / prise de contact
    words: [
      'contact',
      'contactez',
      'joindre',
      'ecrire',
      'message',
      'formulaire',
      'echanger',
      'parlons',
      'contacter',
      'coordonnees',
      'contactus',
      'telephone',
      'appeler',
      'rappeler',
      'rdv',
      'rendez-vous',
      'reservation',
      'reserver',
      'discutons',
      'parlons',
      'call',
    ],
    paths: [
      'contact',
      'contactez',
      'joindre',
      'form',
      'nous-contacter',
      'contactus',
      'write',
      'coordonnees',
      'nous-ecrire',
      'formulaire',
      'adresse',
      'acces',
      'localisation',
      'plan',
      'itineraire',
      'map',
    ],
  },
  {
    // Devis / tarifs / prix
    words: [
      'devis',
      'estimation',
      'chiffrage',
      'tarif',
      'prix',
      'offre',
      'forfait',
      'cout',
      'budget',
      'prestation',
      'gratuit',
      'tarification',
      'honoraires',
      'abonnement',
      'grille',
    ],
    paths: [
      'devis',
      'tarif',
      'tarifs',
      'prix',
      'offre',
      'offres',
      'pricing',
      'forfait',
      'prestation',
      'prestations',
      'honoraires',
      'estimation',
      'abonnements',
    ],
  },
  {
    // Localisation / accès / adresse postale
    // Inclut les mots d'adresse : une ancre "12 rue de la Paix" pointe souvent vers /contact ou /acces
    words: [
      'adresse',
      'acces',
      'localisation',
      'trouver',
      'itineraire',
      'lieu',
      'venir',
      'plan',
      'carte',
      'coordonnees',
      'bureau',
      'siege',
      'agence',
      'acceder',
      // mots d'adresse postale
      'rue',
      'avenue',
      'boulevard',
      'chemin',
      'route',
      'allee',
      'impasse',
      'place',
      'quai',
      'cite',
      'residence',
      'domaine',
      'batiment',
      // localisation géographique
      'ville',
      'quartier',
      'secteur',
      'region',
      'departement',
      'commune',
    ],
    paths: [
      'adresse',
      'acces',
      'access',
      'contact',
      'plan',
      'localisation',
      'trouver',
      'map',
      'itineraire',
      'coordonnees',
      'venir',
      'nous-trouver',
    ],
  },
  {
    // À propos / équipe / entreprise
    words: [
      'equipe',
      'agence',
      'histoire',
      'presentation',
      'propos',
      'entreprise',
      'societe',
      'fondateur',
      'valeurs',
      'cabinet',
      'studio',
      'bureau',
      'dirigeant',
      'identite',
      'mission',
      'vision',
    ],
    paths: [
      'about',
      'qui-sommes',
      'agence',
      'presentation',
      'equipe',
      'histoire',
      'nous',
      'valeurs',
      'cabinet',
      'entreprise',
      'identite',
      'mission',
      'propos',
    ],
  },
  {
    // Services / prestations
    words: [
      'service',
      'prestation',
      'activite',
      'solution',
      'competence',
      'expertise',
      'metier',
      'savoir',
      'offre',
      'accompagnement',
      'domaine',
      'intervention',
      'specialite',
    ],
    paths: [
      'service',
      'services',
      'prestation',
      'prestations',
      'activite',
      'activites',
      'solutions',
      'expertises',
      'domaines',
      'offres',
      'interventions',
    ],
  },
  {
    // Blog / actualités / ressources éditoriales
    words: [
      'blog',
      'article',
      'actualite',
      'news',
      'conseil',
      'guide',
      'ressource',
      'publication',
      'actu',
      'billet',
      'edito',
      'dossier',
      'veille',
      'Tribune',
      'tribune',
    ],
    paths: [
      'blog',
      'articles',
      'actualites',
      'news',
      'conseils',
      'guides',
      'ressources',
      'publications',
      'actu',
      'edito',
      'dossier',
    ],
  },
  {
    // Boutique / produits / e-commerce
    words: [
      'produit',
      'boutique',
      'catalogue',
      'shop',
      'acheter',
      'commande',
      'panier',
      'achat',
      'reference',
      'gamme',
      'collection',
      'assortiment',
    ],
    paths: [
      'produit',
      'produits',
      'boutique',
      'shop',
      'catalogue',
      'acheter',
      'store',
      'ecommerce',
      'gamme',
      'references',
      'collections',
    ],
  },
  {
    // Mentions légales / RGPD / confidentialité
    words: [
      'mention',
      'legal',
      'cgu',
      'cgv',
      'confidentialite',
      'rgpd',
      'cookie',
      'politique',
      'donnees',
      'charte',
      'conditions',
      'protection donnees',
    ],
    paths: [
      'mentions-legales',
      'mentions',
      'legal',
      'cgu',
      'cgv',
      'confidentialite',
      'politique',
      'privacy',
      'donnees',
      'charte',
      'conditions',
    ],
  },
  {
    // Galerie / réalisations / portfolio
    words: [
      'galerie',
      'realisation',
      'portfolio',
      'projet',
      'reference',
      'chantier',
      'travaux',
      'ouvrage',
      'creation',
      'exemple',
      'cas client',
    ],
    paths: [
      'galerie',
      'realisations',
      'portfolio',
      'projets',
      'references',
      'chantiers',
      'creations',
      'exemples',
      'travaux',
      'cas',
    ],
  },
  {
    // Témoignages / avis clients
    words: [
      'temoignage',
      'avis',
      'satisfaction',
      'evaluation',
      'recommandation',
      'note',
      'commentaire',
      'retour client',
      'client content',
      'ils nous font confiance',
    ],
    paths: [
      'temoignages',
      'avis',
      'clients',
      'satisfaction',
      'evaluations',
      'recommandations',
      'retours',
    ],
  },
  {
    // Formation / éducation / apprentissage
    words: [
      'formation',
      'cours',
      'apprentissage',
      'stage',
      'atelier',
      'programme',
      'cursus',
      'module',
      'apprendre',
      'education',
      'enseignement',
      'certification',
      'diplome',
    ],
    paths: [
      'formation',
      'formations',
      'cours',
      'apprentissage',
      'stages',
      'ateliers',
      'programme',
      'modules',
      'certifications',
      'diplomes',
    ],
  },
  {
    // Recrutement / emploi / carrières
    words: [
      'recrutement',
      'emploi',
      'candidature',
      'postuler',
      'carriere',
      'poste',
      'rejoindre',
      'embauche',
      'travail',
      'offre emploi',
      'job',
      'opportunite',
    ],
    paths: [
      'recrutement',
      'emploi',
      'offres-emploi',
      'candidatures',
      'carrieres',
      'postes',
      'rejoindre',
      'jobs',
      'opportunites',
    ],
  },
  {
    // FAQ / aide / support
    words: [
      'faq',
      'aide',
      'question',
      'reponse',
      'support',
      'assistance',
      'probleme',
      'tutoriel',
      'documentation',
      'helpdesk',
      'comment',
      'guidage',
    ],
    paths: [
      'faq',
      'aide',
      'questions',
      'reponses',
      'support',
      'assistance',
      'tutoriels',
      'documentation',
      'help',
      'doc',
    ],
  },
  {
    // Événements / agenda / calendrier
    words: [
      'evenement',
      'agenda',
      'calendrier',
      'date',
      'programme',
      'soiree',
      'conference',
      'festival',
      'salon',
      'foire',
      'inscription evenement',
      'prochaine date',
    ],
    paths: [
      'evenements',
      'agenda',
      'calendrier',
      'programme',
      'soirees',
      'conferences',
      'festivals',
      'salons',
      'dates',
      'events',
    ],
  },
  {
    // Santé / médical / paramédical
    words: [
      'sante',
      'medical',
      'medecin',
      'docteur',
      'soin',
      'soins',
      'consultation',
      'clinique',
      'cabinet',
      'praticien',
      'infirmier',
      'kine',
      'osteopathe',
      'dentiste',
      'opticien',
      'pharmacie',
      'therapie',
      'patient',
      'diagnostic',
      'traitement',
    ],
    paths: [
      'sante',
      'medical',
      'soins',
      'consultation',
      'cabinet',
      'clinique',
      'patients',
      'specialites',
      'pathologies',
      'rdv-medical',
      'prendre-rendez-vous',
    ],
  },
  {
    // Juridique / droit / avocat / notaire
    words: [
      'juridique',
      'droit',
      'avocat',
      'notaire',
      'huissier',
      'justice',
      'litige',
      'contentieux',
      'tribunal',
      'conseil',
      'succession',
      'divorce',
      'penal',
      'civil',
      'fiscal',
      'procedure',
    ],
    paths: [
      'juridique',
      'droit',
      'avocat',
      'avocats',
      'notaire',
      'cabinet',
      'expertises',
      'domaines-intervention',
      'competences',
      'contentieux',
    ],
  },
  {
    // Automobile / garage / mécanique
    words: [
      'auto',
      'automobile',
      'voiture',
      'vehicule',
      'garage',
      'mecanique',
      'carrosserie',
      'reparation',
      'entretien',
      'revision',
      'pneu',
      'pneus',
      'depannage',
      'diagnostic',
      'concessionnaire',
      'occasion',
      'utilitaire',
      'moto',
    ],
    paths: [
      'auto',
      'automobile',
      'vehicules',
      'garage',
      'mecanique',
      'carrosserie',
      'reparation',
      'entretien',
      'occasions',
      'vehicules-occasion',
      'services-auto',
    ],
  },
  {
    // Immobilier / agence / transaction
    words: [
      'immobilier',
      'immo',
      'agence',
      'bien',
      'biens',
      'appartement',
      'maison',
      'terrain',
      'location',
      'vente',
      'achat',
      'estimation',
      'gestion',
      'locative',
      'propriete',
      'logement',
      'neuf',
      'ancien',
      'investissement',
    ],
    paths: [
      'immobilier',
      'immo',
      'biens',
      'annonces',
      'vente',
      'location',
      'achat',
      'estimation',
      'nos-biens',
      'gestion-locative',
      'programmes-neufs',
    ],
  },
  {
    // Restauration / alimentation / traiteur
    words: [
      'restaurant',
      'restauration',
      'cuisine',
      'menu',
      'carte',
      'chef',
      'traiteur',
      'plat',
      'gastronomie',
      'reservation',
      'table',
      'brasserie',
      'bistrot',
      'boulangerie',
      'patisserie',
      'epicerie',
      'cave',
      'degustation',
    ],
    paths: [
      'restaurant',
      'menu',
      'carte',
      'cuisine',
      'traiteur',
      'nos-plats',
      'la-carte',
      'reservation',
      'reserver',
      'menus',
    ],
  },
  {
    // Beauté / coiffure / bien-être / esthétique
    words: [
      'beaute',
      'coiffure',
      'coiffeur',
      'esthetique',
      'estheticienne',
      'soin',
      'soins',
      'massage',
      'spa',
      'institut',
      'maquillage',
      'manucure',
      'onglerie',
      'epilation',
      'bienetre',
      'relaxation',
      'visage',
      'corps',
      'detente',
    ],
    paths: [
      'beaute',
      'coiffure',
      'esthetique',
      'soins',
      'institut',
      'spa',
      'prestations',
      'nos-soins',
      'bien-etre',
      'massages',
    ],
  },
  {
    // Sport / fitness / coaching
    words: [
      'sport',
      'fitness',
      'musculation',
      'coaching',
      'coach',
      'entrainement',
      'club',
      'salle',
      'cours',
      'yoga',
      'pilates',
      'cardio',
      'crossfit',
      'remise',
      'forme',
      'activite',
      'discipline',
    ],
    paths: [
      'sport',
      'fitness',
      'cours',
      'coaching',
      'activites',
      'disciplines',
      'planning',
      'nos-cours',
      'salle',
      'abonnements',
    ],
  },
  {
    // Animaux / vétérinaire / animalerie
    words: [
      'animal',
      'animaux',
      'veterinaire',
      'animalerie',
      'chien',
      'chat',
      'toilettage',
      'elevage',
      'pension',
      'dressage',
      'comportementaliste',
      'soin',
      'nac',
    ],
    paths: [
      'animaux',
      'veterinaire',
      'animalerie',
      'toilettage',
      'pension',
      'nos-animaux',
      'services-animaliers',
      'elevage',
    ],
  },
  {
    // Transport / livraison / logistique / déménagement
    words: [
      'transport',
      'livraison',
      'logistique',
      'demenagement',
      'demenageur',
      'colis',
      'fret',
      'expedition',
      'messagerie',
      'coursier',
      'stockage',
      'entreposage',
      'acheminement',
      'flotte',
    ],
    paths: [
      'transport',
      'livraison',
      'logistique',
      'demenagement',
      'nos-services',
      'fret',
      'stockage',
      'expedition',
    ],
  },
  {
    // Finance / assurance / comptabilité / banque
    words: [
      'finance',
      'assurance',
      'mutuelle',
      'banque',
      'credit',
      'pret',
      'comptabilite',
      'comptable',
      'gestion',
      'patrimoine',
      'investissement',
      'fiscalite',
      'epargne',
      'placement',
      'courtier',
      'garantie',
      'contrat',
      'prevoyance',
    ],
    paths: [
      'finance',
      'assurance',
      'assurances',
      'mutuelle',
      'credit',
      'comptabilite',
      'gestion',
      'patrimoine',
      'nos-offres',
      'solutions',
      'produits',
    ],
  },
  {
    // Bâtiment / travaux / rénovation / artisanat
    words: [
      'batiment',
      'travaux',
      'renovation',
      'construction',
      'maconnerie',
      'menuiserie',
      'plomberie',
      'electricite',
      'peinture',
      'carrelage',
      'toiture',
      'isolation',
      'amenagement',
      'chantier',
      'artisan',
      'btp',
      'gros',
      'oeuvre',
    ],
    paths: [
      'travaux',
      'renovation',
      'construction',
      'batiment',
      'nos-travaux',
      'realisations',
      'chantiers',
      'prestations',
      'savoir-faire',
      'metiers',
    ],
  },
  {
    // Énergie / chauffage / climatisation / plomberie
    words: [
      'chauffage',
      'climatisation',
      'energie',
      'energetique',
      'pompe',
      'chaleur',
      'chaudiere',
      'solaire',
      'photovoltaique',
      'ventilation',
      'isolation',
      'thermique',
      'plomberie',
      'sanitaire',
      'depannage',
      'installation',
      'entretien',
    ],
    paths: [
      'chauffage',
      'climatisation',
      'energie',
      'energies',
      'pompe-chaleur',
      'solaire',
      'plomberie',
      'sanitaire',
      'nos-services',
      'installations',
    ],
  },
  {
    // Accueil / retour page principale
    words: ['accueil', 'home', 'retour', 'principal', 'page accueil'],
    paths: ['/', ''],
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Synonymes sémantiques — groupes de tokens interchangeables
//
// Quand un token de l'ancre appartient à un groupe, tous les membres du groupe
// sont testés contre les segments de l'URL (et inversement). Cela permet de
// détecter des correspondances valides que le Levenshtein seul ne peut pas
// trouver (ex: "bassin" ↔ "piscine", "demandez" ↔ "contact").
// ─────────────────────────────────────────────────────────────────────────────
export const SYNONYM_GROUPS: string[][] = [
  // ════════════════════════════════════════════════════════════════════════════
  // BÂTIMENT / TRAVAUX / EXTÉRIEUR
  // ════════════════════════════════════════════════════════════════════════════

  // ── Eau / piscine / détente aquatique ─────────────────────────────────────
  [
    'piscine',
    'bassin',
    'spa',
    'jacuzzi',
    'natation',
    'aquatique',
    'bain',
    'nage',
    'baignade',
    'chlore',
    'filtration',
    'traitement eau',
    'liner',
    'margelle',
    'coque',
    'gonflable',
    'robot piscine',
    'pompe filtration',
    'sauna',
    'balneo',
    'hydro',
    'aqua',
  ],

  // ── Rénovation / modernisation / restauration ─────────────────────────────
  [
    'renovation',
    'refection',
    'modernisation',
    'restauration',
    'restaurer',
    'rehabiliter',
    'rehabilitation',
    'remise etat',
    'rajeunissement',
    'rafraichissement',
    'ravalement',
    'transformation',
    'lifting',
    'relooke',
    'travaux renovation',
    'renovation interieure',
    'renovation exterieure',
    'remise neuf',
  ],

  // ── Toiture / couverture / charpente ─────────────────────────────────────
  [
    'toiture',
    'toit',
    'charpente',
    'tuile',
    'bardage',
    'zinguerie',
    'gouttiere',
    'couvreur',
    'couverture',
    'ardoise',
    'faitage',
    'impermeabilisation',
    'etancheite',
    'isolation toit',
    'couverture zinc',
    'cuivre',
    'toiture plate',
    'toiture terrasse',
    'charpentier',
    'sous toiture',
    'lucarne',
    'velux',
    'chatiere',
  ],

  // ── Abri / pergola / store / protection extérieure ────────────────────────
  [
    'abri',
    'bache',
    'protection',
    'couvrir',
    'proteger',
    'auvent',
    'carport',
    'pergola',
    'tonnelle',
    'marquise',
    'store',
    'parasol',
    'tente',
    'voile ombrage',
  ],

  // ── Menuiserie / porte / fenêtre / bois / alu / PVC ─────────────────────
  [
    'menuiserie',
    'menuisier',
    'bois',
    'porte',
    'fenetre',
    'volet',
    'parquet',
    'escalier',
    'boiserie',
    'chassis',
    'baie vitree',
    'aluminium',
    'alu',
    'pvc',
    'double vitrage',
    'triple vitrage',
    'isolation phonique',
    'isolation acoustique',
    'brise soleil',
    'occultant',
    'store interieur',
    'store exterieur',
    'portail',
    'cloture',
  ],

  // ── Maçonnerie / gros œuvre / construction ───────────────────────────────
  [
    'maconnerie',
    'macon',
    'beton',
    'construction',
    'bati',
    'batiment',
    'fondation',
    'dalle',
    'mur',
    'parpaing',
    'agglo',
    'percement',
    'agrandissement',
    'extension',
    'surélévation',
    'surelevation',
    'dallage',
    'pavage',
    'crepissage',
  ],

  // ── Carrelage / revêtements de sol ───────────────────────────────────────
  [
    'carrelage',
    'carreleur',
    'sol',
    'revetement sol',
    'stratifie',
    'vinyle',
    'vinyl',
    'moquette',
    'pose carrelage',
    'faience',
    'gravier',
    'terrasse bois',
    'terrasse composite',
    'pierre naturelle',
    'granit',
    'marbre',
    'travertin',
  ],

  // ── Peinture / décoration intérieure / ravalement ────────────────────────
  [
    'peinture',
    'decoration',
    'peintre',
    'papier peint',
    'enduit',
    'badigeon',
    'revetement',
    'couleur',
    'teinture',
    'lasure',
    'facade',
    'ravalement facade',
    'sticker',
    'trompe oeil',
    'enduit decoratif',
    'beton cire',
    'venetien',
    'tadelakt',
    'toile verre',
    'peindre',
    'impermeabilisant',
  ],

  // ── Plomberie / sanitaire / eau ───────────────────────────────────────────
  [
    'plomberie',
    'plombier',
    'tuyau',
    'tuyauterie',
    'sanitaire',
    'evacuation',
    'robinetterie',
    'chauffe eau',
    'fuites',
    'debouchage',
    'canalisation',
    'fosse septique',
    'pompe relevage',
    'surpresseur',
    'adoucisseur eau',
    'compteur eau',
    'fuite eau',
    'degat eau',
    'robinet',
    'mitigeur',
    'assainissement',
  ],

  // ── Salle de bain / douche / bains ───────────────────────────────────────
  [
    'douche',
    'baignoire',
    'lavabo',
    'vasque',
    'salle bain',
    'sanitaires',
    'receveur',
    'mitigeur thermostatique',
    'douche italienne',
    'bain nordique',
    'salle eau',
    'hammam sanitaire',
    'robinetterie salle bain',
  ],

  // ── Électricité / domotique / énergies ────────────────────────────────────
  [
    'electricite',
    'electricien',
    'electrique',
    'cablage',
    'tableau',
    'installation electrique',
    'disjoncteur',
    'prises',
    'eclairage',
    'domotique',
    'automatisme',
    'borne recharge',
    'groupe electrogene',
    'onduleur',
    'led',
    'eclairage led',
    'interrupteur',
    'minuterie',
  ],

  // ── Chauffage / climatisation / isolation thermique ──────────────────────
  [
    'chauffage',
    'chaudiere',
    'radiateur',
    'thermique',
    'chaleur',
    'climatisation',
    'pompe chaleur',
    'poele',
    'chauffagiste',
    'energetique',
    'ventilation',
    'vmc',
    'isolation thermique',
    'plancher chauffant',
    'pac',
    'solaire thermique',
    'chaudiere gaz',
    'chaudiere fioul',
    'granule',
    'pellet',
    'climatiseur',
    'reversible',
  ],

  // ── Énergies renouvelables / solaire / écologie ───────────────────────────
  [
    'photovoltaique',
    'solaire',
    'panneaux solaires',
    'eolien',
    'biomasse',
    'geothermie',
    'autoconsommation',
    'enr',
    'energie verte',
    'transition energetique',
    'ecologie',
    'ecologique',
    'economies energie',
    'bilan carbone',
    'isolation ecologique',
  ],

  // ── Jardin / paysagisme / végétal ────────────────────────────────────────
  [
    'jardin',
    'exterieur',
    'terrasse',
    'amenagement',
    'paysager',
    'paysagiste',
    'outdoor',
    'espace vert',
    'pelouse',
    'tondeuse',
    'arrosage',
    'plantation',
    'haie',
    'gazon',
    'taille haie',
    'elagage',
    'abattage',
    'arbre',
    'fleur',
    'massif',
    'potager',
    'compost',
    'tonte',
    'fauchage',
    'engazonnement',
  ],

  // ── Sécurité / surveillance / contrôle d'accès ───────────────────────────
  [
    'securite',
    'surveillance',
    'alarme',
    'gardiennage',
    'videosurveillance',
    'controle acces',
    'serrurerie',
    'telesurveillance',
    'portier',
    'interphone',
    'digicode',
    'badge',
    'anti-intrusion',
    'detection incendie',
    'extincteur',
    'alarme incendie',
    'systeme securite',
    'camera',
    'video surveillance',
  ],

  // ════════════════════════════════════════════════════════════════════════════
  // SERVICES / PROFESSIONS
  // ════════════════════════════════════════════════════════════════════════════

  // ── Adresse postale / localisation physique ──────────────────────────────
  // "rue Victor Hugo" ou "avenue du Général de Gaulle" → /contact ou /acces
  [
    'adresse',
    'rue',
    'avenue',
    'boulevard',
    'chemin',
    'route',
    'allee',
    'impasse',
    'place',
    'quai',
    'cite',
    'residence',
    'domaine',
    'batiment',
    'localisation',
    'coordonnees',
    'acces',
    'plan',
    'itineraire',
    'trouver',
    'venir',
    'siege',
    'agence',
    'bureau',
    'cabinet',
    'etage',
    'entree',
  ],

  // ── Téléphone / contact vocal ─────────────────────────────────────────────
  // "06 12 34 56 78" ou "Appelez-nous" → /contact
  [
    'telephone',
    'tel',
    'appel',
    'appeler',
    'rappel',
    'rappeler',
    'joindre',
    'contact',
    'appel',
    'num',
    'numero',
    'portable',
    'mobile',
    'fixe',
    'hotline',
  ],

  // ── Contact / demande / rendez-vous ──────────────────────────────────────
  // Note : multi-mots supprimés (jamais retrouvés après tokenisation individuelle)
  [
    'contact',
    'contacter',
    'demande',
    'demandez',
    'demander',
    'solliciter',
    'joindre',
    'ecrire',
    'coordonnees',
    'renseigner',
    'renseignement',
    'appeler',
    'telephone',
    'rappeler',
    'rappel',
    'rdv',
    'formulaire',
    'parlons',
    'discutons',
    'echanger',
  ],

  // ── Réservation / agenda / booking ───────────────────────────────────────
  // Note : "prendre rdv" / "prendre rendez-vous" supprimés (multi-mots)
  [
    'reservation',
    'reserver',
    'rdv',
    'agenda',
    'disponibilite',
    'creneau',
    'booking',
    'planifier',
    'rendez-vous',
    'slot',
    'calendar',
    'creneaux',
  ],

  // ── Devis / tarification / simulation ────────────────────────────────────
  // Note : multi-mots supprimés
  [
    'devis',
    'estimation',
    'tarif',
    'chiffrage',
    'budget',
    'offre',
    'honoraires',
    'forfait',
    'abonnement',
    'cotisation',
    'tarification',
    'simulation',
    'calculer',
    'estimer',
    'tarifs',
    'prix',
    'cout',
    'grille',
    'gratuit',
  ],

  // ── Nettoyage / entretien / hygiène ──────────────────────────────────────
  // Note : multi-mots supprimés
  [
    'nettoyage',
    'entretien',
    'menage',
    'pressing',
    'lavage',
    'detartrage',
    'hygiene',
    'proprete',
    'desinfection',
    'assainissement',
    'deratisation',
    'desinsectisation',
    'vapeur',
    'pression',
  ],

  // ── Santé / médical / bien-être ───────────────────────────────────────────
  [
    'sante',
    'medecin',
    'docteur',
    'consultation',
    'soins',
    'bienetre',
    'therapeute',
    'clinique',
    'medical',
    'cabinet medical',
    'praticien',
    'professionnel sante',
    'infirmier',
    'kine',
    'kinesitherapeute',
    'osteopathe',
    'psy',
    'psychologue',
    'podologue',
    'dentiste',
    'opticien',
    'pharmacie',
    'medecine generale',
    'specialiste',
  ],

  // ── Assurance / garantie / prévoyance ────────────────────────────────────
  [
    'assurance',
    'mutuelle',
    'garantie',
    'contrat',
    'sinistre',
    'indemnisation',
    'couverture assurance',
    'responsabilite civile',
    'decennale',
    'multirisque',
    'prevoyance',
    'retraite complementaire',
    'complementaire sante',
    'garantie decennale',
    'assurance pro',
    'assurance habitation',
    'assurance auto',
    'assurance vie',
  ],

  // ── Finance / comptabilité / gestion ─────────────────────────────────────
  [
    'finance',
    'comptabilite',
    'comptable',
    'expert comptable',
    'bilan',
    'fiscalite',
    'investissement',
    'patrimoine',
    'gestion',
    'audit financier',
    'conseil financier',
    'defiscalisation',
    'holding',
    'rachat entreprise',
    'transmission entreprise',
    'levee fonds',
    'financement',
    'credit',
    'pret',
    'emprunt',
    'tresorerie',
  ],

  // ── Transport / livraison / logistique ───────────────────────────────────
  [
    'transport',
    'livraison',
    'expedition',
    'envoi',
    'colis',
    'messagerie',
    'logistique',
    'delai',
    'fret',
    'afretement',
    'groupage',
    'camionnage',
    'livreur',
    'coursier',
    'trajet',
    'acheminement',
    'retrait',
    'point relais',
  ],

  // ── Déménagement / stockage ───────────────────────────────────────────────
  [
    'demenagement',
    'demenageur',
    'emballage',
    'stockage',
    'garde meuble',
    'box',
    'monte meuble',
    'transfert',
    'deplacement',
    'installation demenagement',
  ],

  // ── Emploi / recrutement / carrière ──────────────────────────────────────
  [
    'emploi',
    'recrutement',
    'poste',
    'carriere',
    'candidature',
    'embauche',
    'travail',
    'job',
    'offre emploi',
    'opportunite',
    'alternance',
    'interim',
    'cdi',
    'cdd',
    'freelance',
    'independant',
    'teletravail',
    'profil',
    'cv',
    'lettre motivation',
    'bac pro',
    'master',
    'ingenieur',
  ],

  // ── Formation / éducation / certification ────────────────────────────────
  [
    'formation',
    'cours',
    'apprentissage',
    'stage',
    'atelier',
    'programme',
    'module',
    'certification',
    'diplome',
    'enseignement',
    'elearning',
    'distanciel',
    'presentiel',
    'intra',
    'inter',
    'blended',
    'mooc',
    'certification professionnelle',
    'cpf',
    'financement formation',
    'opco',
    'bilan competences',
  ],

  // ── Web / digital / marketing / communication ────────────────────────────
  [
    'web',
    'digital',
    'numerique',
    'internet',
    'application',
    'logiciel',
    'developpement',
    'informatique',
    'seo',
    'referencement',
    'marketing digital',
    'communication digitale',
    'reseaux sociaux',
    'community manager',
    'agence web',
    'site web',
    'creation site',
    'webdesign',
    'ux',
    'ui',
    'google',
    'adwords',
    'sem',
    'emailing',
    'newsletter',
  ],

  // ── Photo / vidéo / identité visuelle ────────────────────────────────────
  [
    'photo',
    'photographie',
    'video',
    'cliche',
    'reportage',
    'tournage',
    'shooting',
    'audiovisuel',
    'drone',
    'motion design',
    'animation',
    'clip video',
    'film entreprise',
    'portrait',
    'identite visuelle',
    'logo',
    'charte graphique',
    'illustration',
    'graphisme',
    'graphiste',
  ],

  // ── Locaux / espaces professionnels ──────────────────────────────────────
  [
    'local',
    'locaux',
    'bureau',
    'bureaux',
    'espace',
    'espaces',
    'surface',
    'surfaces',
    'salle',
    'pieces',
    'lieu',
    'lieux',
    'batiment',
    'batiments',
    'immeuble',
  ],

  // ── Industriel / professionnel / entreprise ───────────────────────────────
  [
    'industriel',
    'industriels',
    'industrie',
    'professionnel',
    'professionnels',
    'pros',
    'entreprise',
    'entreprises',
    'commercial',
    'commerciale',
    'tertiaire',
    'artisan',
  ],

  // ── Juridique / droit / professions du droit ──────────────────────────────
  [
    'juridique',
    'droit',
    'avocat',
    'avocate',
    'notaire',
    'huissier',
    'juriste',
    'justice',
    'litige',
    'contentieux',
    'tribunal',
    'procedure',
    'plaidoirie',
    'succession',
    'divorce',
    'penal',
    'civil',
    'fiscal',
    'social',
    'conseil juridique',
    'cabinet avocat',
    'mediation',
  ],

  // ── Conseil / accompagnement / stratégie ──────────────────────────────────
  [
    'conseil',
    'accompagnement',
    'strategie',
    'consulting',
    'consultant',
    'expertise',
    'audit',
    'diagnostic',
    'optimisation',
    'transformation',
    'pilotage',
    'coaching',
    'management',
    'gestion',
    'organisation',
    'performance',
    'developpement',
  ],

  // ── Artisanat / fabrication / sur-mesure ──────────────────────────────────
  [
    'artisan',
    'artisanat',
    'fabrication',
    'fabrique',
    'atelier',
    'savoir-faire',
    'fait main',
    'sur-mesure',
    'mesure',
    'creation',
    'confection',
    'production',
    'manufacture',
    'facon',
  ],

  // ════════════════════════════════════════════════════════════════════════════
  // IMMOBILIER
  // ════════════════════════════════════════════════════════════════════════════

  // ── Habitation / immobilier bâti ──────────────────────────────────────────
  [
    'maison',
    'habitation',
    'logement',
    'domicile',
    'residence',
    'habitat',
    'villa',
    'pavillon',
    'immeuble',
    'batiment',
    'maison individuelle',
    'maison neuve',
    'construction maison',
    'plain pied',
    'plain-pied',
  ],

  // ── Appartement / location ────────────────────────────────────────────────
  [
    'appartement',
    'studio',
    'louer',
    'location',
    'locataire',
    'bail',
    'loyer',
    'colocation',
    'chambre location',
    'meuble',
    'non meuble',
    'bail mobilite',
  ],

  // ── Immobilier transaction / achat-vente ─────────────────────────────────
  [
    'vente',
    'achat immobilier',
    'agence immobiliere',
    'notaire',
    'estimation immobilier',
    'mandat',
    'visite',
    'compromis',
    'signature',
    'investissement locatif',
    'bien immobilier',
    'propriete',
    'foncier',
    'promoteur',
    'programme neuf',
  ],

  // ════════════════════════════════════════════════════════════════════════════
  // LOISIRS / TOURISME / GASTRONOMIE
  // ════════════════════════════════════════════════════════════════════════════

  // ── Cuisine / gastronomie / restauration ────────────────────────────────
  [
    'cuisine',
    'culinaire',
    'gastronomie',
    'restaurant',
    'chef',
    'recette',
    'plat',
    'repas',
    'menu',
    'alimentation',
    'traiteur',
    'buffet',
    'patisserie',
    'boulangerie',
    'gastronomique',
    'bistronomie',
    'reservation table',
    'pizza',
    'sushi',
    'burger',
    'epicerie',
    'carte restaurant',
  ],

  // ── Hôtel / hébergement / voyage / tourisme ──────────────────────────────
  [
    'hotel',
    'hebergement',
    'chambre',
    'sejour',
    'gite',
    'pension',
    'voyage',
    'vacances',
    'tourisme',
    'escapade',
    'auberge',
    'chambre hotes',
    'resort',
    'club vacances',
    'all inclusive',
    'spa hotel',
    'thalasso',
    'cure thermale',
    'week end',
    'destination',
    'circuit',
    'croisiere',
  ],

  // ── Événement / cérémonie / soirée ───────────────────────────────────────
  [
    'evenement',
    'soiree',
    'festival',
    'concert',
    'spectacle',
    'animation',
    'reception',
    'ceremonie',
    'anniversaire',
    'mariage',
    'gala',
    'cocktail',
    'inauguration',
    'seminaire',
    'team building',
    'banquet',
    'bal',
    'communion',
    'bapteme',
    'conference',
    'congres',
    'salon professionnel',
  ],

  // ── Sport / fitness / activité physique ──────────────────────────────────
  [
    'sport',
    'fitness',
    'musculation',
    'yoga',
    'pilates',
    'entrainement',
    'coaching sportif',
    'club sport',
    'randonnee',
    'cyclisme',
    'velo',
    'running',
    'course pied',
    'triathlon',
    'surf',
    'ski',
    'snowboard',
    'tennis',
    'golf',
    'padel',
    'escalade',
    'aquagym',
    'gym',
    'aerobic',
    'crossfit',
    'boxe',
    'arts martiaux',
    'natation loisir',
  ],

  // ── Viticulture / vin / terroir ───────────────────────────────────────────
  [
    'vin',
    'vigne',
    'viticulteur',
    'domaine',
    'chateau',
    'cru',
    'appellation',
    'vignoble',
    'cave',
    'vinification',
    'vendange',
    'terroir',
    'degustation',
    'oenologie',
    'sommelier',
    'millesime',
    'cuvee',
  ],

  // ════════════════════════════════════════════════════════════════════════════
  // MODE / BEAUTÉ / BIEN-ÊTRE
  // ════════════════════════════════════════════════════════════════════════════

  // ── Mode / vêtement / accessoire ─────────────────────────────────────────
  [
    'mode',
    'vetement',
    'textile',
    'habit',
    'robe',
    'costume',
    'couture',
    'accessoire',
    'bijou',
    'sac',
    'chaussure',
    'luxe',
    'pret a porter',
    'sur mesure',
    'couturier',
    'styliste',
    'tendance',
    'collection',
    'tenue',
  ],

  // ── Beauté / coiffure / soins corps ──────────────────────────────────────
  [
    'beaute',
    'coiffure',
    'coiffeur',
    'esthetique',
    'maquillage',
    'soin visage',
    'onglerie',
    'manucure',
    'pedicure',
    'massage beaute',
    'relaxation',
    'detente',
    'soins corps',
    'lifting visage',
    'peeling',
    'epilation',
    'laser beaute',
    'soin anti age',
    'soin hydratant',
  ],

  // ── Animal de compagnie / vétérinaire ────────────────────────────────────
  [
    'animal',
    'chien',
    'chat',
    'veterinaire',
    'animalerie',
    'elevage',
    'toilettage',
    'pension animaux',
    'nac',
    'aquarium',
    'oiseau',
    'lapin',
    'alimentation animale',
    'accessoire animal',
  ],

  // ════════════════════════════════════════════════════════════════════════════
  // E-COMMERCE — TUNNEL D'ACHAT & COMPTE CLIENT
  // ════════════════════════════════════════════════════════════════════════════

  // ── Compte client / espace personnel ─────────────────────────────────────
  // "mon compte" ↔ /account, /mon-compte, /espace-client
  [
    'compte',
    'mon compte',
    'espace client',
    'espace personnel',
    'compte client',
    'profil',
    'account',
    'dashboard client',
    'mes informations',
    'tableau de bord',
  ],

  // ── Connexion / inscription / authentification ────────────────────────────
  // "se connecter" ↔ /login, /connexion, /signin, /creer-compte
  [
    'connexion',
    'login',
    'seconnecter',
    'sincrire',
    'creer compte',
    'inscription',
    'enregistrement',
    'mot de passe',
    'reinitialiser',
    'mdp',
    'identifiants',
    'acces',
    'signin',
    'signup',
    'register',
  ],

  // ── Panier / liste d'achats ───────────────────────────────────────────────
  // "mon panier" ↔ /cart, /panier, /basket
  [
    'panier',
    'cart',
    'basket',
    'ma selection',
    'liste achats',
    'liste envies',
    'wishlist',
    'favoris',
    'articles selectionnes',
    'ajouter panier',
    'mon panier',
  ],

  // ── Paiement / règlement / checkout ──────────────────────────────────────
  // "procéder au paiement" ↔ /checkout, /paiement, /reglement
  [
    'paiement',
    'payer',
    'reglement',
    'transaction',
    'checkout',
    'carte bancaire',
    'virement',
    'facture',
    'prelevement',
    'paiement securise',
    'paiement en ligne',
    'paypal',
    'cb',
    'stripe',
    'finaliser commande',
    'proceder paiement',
  ],

  // ── Commande / suivi de commande ─────────────────────────────────────────
  // "suivre ma commande" ↔ /mes-commandes, /order, /tracking
  [
    'commande',
    'mes commandes',
    'suivi commande',
    'order',
    'tracking',
    'suivi colis',
    'livraison commande',
    'expedition commande',
    'statut commande',
    'confirmation commande',
    'historique commandes',
    'numero commande',
  ],

  // ── Promotions / réductions / soldes ─────────────────────────────────────
  // "nos promos" ↔ /soldes, /promotions, /bons-plans
  [
    'promo',
    'promotion',
    'reduction',
    'solde',
    'remise',
    'code promo',
    'coupon',
    'discount',
    'offre speciale',
    'vente flash',
    'destockage',
    'bonne affaire',
    'prix reduit',
    'prix barre',
    'economie',
    'bon plan',
  ],

  // ── Retour / remboursement / SAV ─────────────────────────────────────────
  // "retourner un article" ↔ /retours, /remboursement, /sav
  [
    'retour',
    'remboursement',
    'rembourser',
    'retourner',
    'echange',
    'sav',
    'service apres vente',
    'reclamation',
    'litige',
    'retractation',
    'satisfait rembourse',
    'politique retour',
    'retour produit',
  ],

  // ── Fiche produit / description technique ────────────────────────────────
  // "voir les caractéristiques" ↔ /fiche-produit, /detail, /specifications
  [
    'fiche produit',
    'caracteristiques',
    'specifications',
    'description produit',
    'detail produit',
    'fiche technique',
    'notice',
    'datasheet',
    'detail article',
    'informations produit',
  ],

  // ════════════════════════════════════════════════════════════════════════════
  // RÉALISATIONS / CONTENU / RESSOURCES
  // ════════════════════════════════════════════════════════════════════════════

  // ── Réalisations / portfolio / projets ───────────────────────────────────
  [
    'realisation',
    'portfolio',
    'projet',
    'chantier',
    'creation',
    'ouvrage',
    'travaux',
    'reference client',
    'cas usage',
    'etude cas',
    'avant apres',
    'nos travaux',
    'nos creations',
  ],

  // ── Avis / témoignages clients ───────────────────────────────────────────
  [
    'avis',
    'temoignage',
    'satisfaction',
    'evaluation',
    'recommandation',
    'note',
    'commentaire',
    'retour experience',
    'feedback',
    'notation',
    'etoile',
    'top client',
    'client satisfait',
    'ils nous font confiance',
    'ce que disent nos clients',
  ],

  // ── Téléchargement / ressource / document ────────────────────────────────
  [
    'telechargement',
    'telecharger',
    'ressource',
    'document',
    'fichier',
    'pdf',
    'support',
    'brochure',
    'catalogue pdf',
    'fiche technique',
    'documentation technique',
    'livre blanc',
    'guide gratuit',
    'contenu premium',
    'notice',
  ],

  // ── Découvrir / explorer ──────────────────────────────────────────────────
  [
    'decouvrir',
    'explorer',
    'consulter',
    'visualiser',
    'parcourir',
    'decouvrez',
    'decouverte',
    'visionner',
    'regarder',
    'acceder',
  ],

  // ════════════════════════════════════════════════════════════════════════════
  // VÉHICULE / HABITATION / DIVERS
  // ════════════════════════════════════════════════════════════════════════════

  // ── Véhicule / automobile ─────────────────────────────────────────────────
  [
    'voiture',
    'vehicule',
    'auto',
    'automobile',
    'camion',
    'utilitaire',
    'moto',
    'deux-roues',
    'voiture electrique',
    'hybride',
    'scooter',
    'van',
    'fourgon',
    'vehicule utilitaire',
    'car',
    'location vehicule',
    'flotte',
  ],

  // ── Enfant / jeunesse / pédagogie ────────────────────────────────────────
  [
    'enfant',
    'enfants',
    'bebe',
    'junior',
    'jeunesse',
    'kid',
    'creche',
    'garderie',
    'pedagogie',
    'nourrisson',
    'bambin',
    'adolescent',
    'ado',
    'enfance',
    'nourrice',
    'assistante maternelle',
    'ecole',
    'college',
    'lycee',
    'scolaire',
    'parascolaire',
  ],

  // ── Taille / format réduit ────────────────────────────────────────────────
  [
    'compact',
    'petit',
    'petite',
    'mini',
    'reduit',
    'reduite',
    'small',
    'leger',
    'etroit',
    'minimaliste',
    'economique',
  ],

  // ── Descripteur de format / modèle / variante ────────────────────────────
  ['format', 'modele', 'version', 'gamme', 'type', 'variante', 'declinaison'],

  // ── Grand / spacieux / large ──────────────────────────────────────────────
  ['grand', 'grande', 'large', 'spacieux', 'genereux', 'maxi', 'jumbo', 'xxl'],
];

export const STOPWORDS = new Set([
  // Articles, prépositions, pronoms FR
  'le',
  'la',
  'les',
  'de',
  'du',
  'des',
  'un',
  'une',
  'et',
  'en',
  'au',
  'aux',
  'ce',
  'se',
  'sa',
  'son',
  'sur',
  'pour',
  'par',
  'avec',
  'dans',
  'qui',
  'que',
  'ou',
  'y',
  'votre',
  'notre',
  'nos',
  'vos',
  'mon',
  'ma',
  'mes',
  'ses',
  'leur',
  'leurs',
  'cet',
  'cette',
  'ces',
  'tout',
  'tous',
  'toute',
  'toutes',
  // Adverbes, conjonctions, prépositions FR supplémentaires
  'si',
  'mais',
  'donc',
  'car',
  'puis',
  'bien',
  'tres',
  'peu',
  'avant',
  'apres',
  'sous',
  'vers',
  'entre',
  'contre',
  'dont',
  'deja',
  'encore',
  'jamais',
  'toujours',
  'souvent',
  'parfois',
  'meme',
  'alors',
  'ainsi',
  'aussi',
  'trop',
  'assez',
  'lors',
  'sans',
  'sauf',
  'selon',
  'afin',
  'soit',
  'tant',
  'lors',
  // Qualificatifs génériques sans valeur sémantique propre (anchor + URL)
  'autre',
  'autres',
  'divers',
  'diverses',
  'plusieurs',
  'certain',
  'certains',
  // Articles, prépositions, pronoms EN
  'the',
  'of',
  'and',
  'in',
  'to',
  'for',
  'with',
  'by',
  'from',
  'at',
  'this',
  'that',
  'are',
  'is',
  'an',
  'as',
  'be',
  'but',
  'not',
  'or',
  'on',
  'it',
  // Auxiliaires, pronoms, adverbes EN supplémentaires
  'we',
  'you',
  'he',
  'she',
  'they',
  'our',
  'his',
  'her',
  'its',
  'can',
  'will',
  'do',
  'did',
  'was',
  'all',
  'if',
  'so',
  'no',
  'up',
  'out',
  'when',
  'how',
  'just',
  'than',
  'too',
  'still',
  'about',
  'over',
  'into',
  'then',
  'there',
  'where',
  'while',
  'been',
  'has',
  'have',
]);

// ─────────────────────────────────────────────────────────────────────────────
// Ancres génériques — aucune valeur sémantique
// ─────────────────────────────────────────────────────────────────────────────
export const GENERIC_ANCHORS = new Set([
  // Navigation vague / formules sans destination
  'cliquez ici',
  'cliquer ici',
  'ici',
  'en savoir plus',
  'savoir plus',
  'lire la suite',
  'voir plus',
  'voir tout',
  'decouvrir',
  'suite',
  'plus',
  'more',
  'click here',
  'read more',
  'learn more',
  'voir',
  'acceder',
  'acceder ici',
  'go',
  'link',
  'lien',
  'page',
  'continuer',
  'suivant',
  'next',
  'voir detail',
  'detail',
  'details',
  // Retour / navigation arrière
  'retour',
  'revenir',
  'back',
  'precedent',
  'previous',
  'retour arriere',
  // Téléchargement sans précision
  'telecharger',
  'telechargez',
  'download',
  'telecharger le document',
  // Actions de validation / formulaire
  'valider',
  'confirmer',
  'ok',
  'submit',
  'envoyer',
  'envoyer le formulaire',
  'envoyer maintenant',
  // Verbes d'accès vagues
  'entrer',
  'entrez',
  'enter',
  'ouvrir',
  'open',
  'fermer',
  'close',
  'quitter',
  // Partage / impression (hors destination)
  'partager',
  'share',
  'imprimer',
  'print',
  // Recherche sans contexte
  'rechercher',
  'recherche',
  'search',
  'chercher',
  // CTA sans valeur sémantique
  'commencer',
  'demarrer',
  'start',
  'commencez maintenant',
  'demarrer maintenant',
  'en profiter',
  'profitez',
  'profitez en',
  'j en profite',
  'decouvrez',
  'je decouvre',
  'je consulte',
  'essayer',
  'essayez',
  'try',
  'try now',
  'choisir',
  'choisissez',
  'selectionner',
  'allez',
  'venez',
  'venez nous voir',
  'voir la suite',
  'voir davantage',
  'voir plus loin',
  'en voir plus',
  // Références au site lui-même
  'notre site',
  'le site',
  'ce site',
  'site web',
  'notre site web',
  'cliquez maintenant',
  'agir maintenant',
  'agissez',
  // Variations anglaises supplémentaires
  'view all',
  'view more',
  'see more',
  'see all',
  'find out more',
  'get started',
  'learn more about',
  'discover',
  'explore',
]);
